services:
  redis:
    image: redis:7

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: outline
      POSTGRES_DB: outline
    volumes:
      - pgdata:/var/lib/postgresql/data

  outline:
    image: outline:local   # or your ECR image URI
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      URL: http://localhost:3000
      PORT: 3000
      DATABASE_URL: postgres://outline:outline@postgres:5432/outline
      REDIS_URL: redis://redis:6379
      SECRET_KEY: "change-me-change-me-change-me-change-me"
      UTILS_SECRET: "change-me-change-me-change-me-change-me"
      PGSSLMODE: disable


volumes:
  pgdata:
