name: Terraform Plan

on:
  pull_request:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type PLAN to run"
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

defaults:
  run:
    working-directory: ./Infra

jobs:
  plan:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.confirm == 'PLAN' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint
        run: tflint --recursive

      - name: Terraform plan
        run: terraform plan
